name: Go Tests in Docker

on:
  push:
    branches:
      - main  # or any other branch you'd like to target
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (optional, for caching)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-go-app-test .

      - name: Run tests inside Docker
        run: docker run --rm my-go-app-test
